backend:
  name: git-gateway
  branch: main

media_folder: "imagenes"  # Carpeta donde se suben imágenes
public_folder: "/imagenes"  # Ruta pública de imágenes

collections:
  # Editar la página principal (index.html)
  - name: "pagina_principal"
    label: "Página Principal"
    files:
      - name: "inicio"
        label: "Contenido Principal"
        file: "index.html"  # Ruta al archivo HTML
        fields:
          # Hero Section
          - { name: "titulo_hero", label: "Título Hero (h1)", widget: "string", required: false }
          - { name: "texto_boton_hero", label: "Texto Botón Hero", widget: "string" }
          
          # Sobre Nosotros
          - { name: "titulo_sobre_nosotros", label: "Título 'Sobre Nosotros'", widget: "string" }
          - { name: "texto_sobre_nosotros", label: "Texto 'Sobre Nosotros'", widget: "markdown" }
          - { name: "texto_imagen_sobre", label: "Texto sobre imagen (¡Te invito...)", widget: "text" }

          # Aquagym
          - { name: "titulo_aquagym", label: "Título Aquagym", widget: "string" }
          - { name: "descripcion_aquagym", label: "Descripción Aquagym", widget: "markdown" }
          - { name: "horarios_aquagym", label: "Horarios Aquagym", widget: "markdown" }
          - { name: "texto_fijo_aquagym", label: "Texto fijo Aquagym", widget: "text" }

          # Matronatación
          - { name: "titulo_matronatacion", label: "Título Matronatación", widget: "string" }
          - { name: "descripcion_matronatacion", label: "Descripción Matronatación", widget: "markdown" }
          - { name: "texto_fijo_matronatacion", label: "Texto fijo Matronatación", widget: "text" }

          # Natación
          - { name: "titulo_natacion", label: "Título Natación", widget: "string" }
          - { name: "descripcion_natacion", label: "Descripción Natación", widget: "markdown" }
          - { name: "texto_fijo_natacion", label: "Texto fijo Natación", widget: "text" }

          # Contacto
          - { name: "telefono_contacto", label: "Teléfono de Contacto", widget: "string" }
          - { name: "email_contacto", label: "Email de Contacto", widget: "string" }
          - { name: "direccion_contacto", label: "Dirección", widget: "text" }

  # Colección para textos repetibles (ej: beneficios)
  - name: "beneficios"
    label: "Beneficios"
    folder: "data/beneficios"  # Crear esta carpeta
    create: true
    fields:
      - { name: "titulo", label: "Título Beneficio", widget: "string" }
      - { name: "descripcion", label: "Descripción", widget: "text" }
      - { name: "icono", label: "Icono (FontAwesome)", widget: "string" }
  # Galería de Aquagym (imágenes + vídeos)
  - name: "aquagym"
    label: "Aquagym - Galería"
    description: "Sube o elimina imágenes/vídeos para la galería de Aquagym"
    folder: "imagenes/Aquagym"  # Ruta donde se guardarán
    create: true  # Permite crear nuevos archivos
    allow_media_large: true  # Permite vídeos pesados
    fields:
      - { name: "body", label: "Archivo", widget: "image", allow_multiple: true }

  # Galería de Matronatación
  - name: "matronatacion"
    label: "Matronatación - Galería"
    folder: "imagenes/matronatacion"
    create: true
    allow_media_large: true
    fields:
      - { name: "body", label: "Archivo", widget: "image", allow_multiple: true }

  # Galería de Natación
  - name: "natacion"
    label: "Natación - Galería"
    folder: "imagenes/natacion"
    create: true
    allow_media_large: true
    fields:
      - { name: "body", label: "Archivo", widget: "image", allow_multiple: true }
