backend:
  name: git-gateway
  branch: main
media_folder: "imagenes"
public_folder: "/imagenes"
publish_mode: editorial_workflow

collections:
  - name: "pagina_principal"
    label: "Página Principal"
    editor:
      preview: false
    files:
      - name: "inicio"
        label: "Contenido Principal"
        file: "../index.html"
        frontmatter_delimiter: ["<!-- CMS-DATA -->", "<!-- /CMS-DATA -->"]
        fields:
          # -------------------------------
          # 1. Hero Section
          # -------------------------------
          - label: "Hero Banner"
            name: "hero"
            widget: "object"
            required: false
            fields:
              - { name: "titulo", label: "Título Principal", widget: "string", required: false }
              - { name: "texto_boton", label: "Texto Botón Principal", widget: "string", required: false }
              - { name: "texto_boton_whatsapp", label: "Texto Botón WhatsApp", widget: "string", required: false }

          # -------------------------------
          # 2. Sobre Nosotros
          # -------------------------------
        
  - name: "sobre"
    label: "Sección Sobre Nosotros"
    folder: "cms/sobre"
    create: false
    slug: "contenido"
    fields:
      - label: "Título de la sección"
        name: "titulo_seccion"
        widget: "string"
        default: "Sobre nosotros"

      - label: "Texto sobre la imagen"
        name: "texto_imagen"
        widget: "text"
        default: "¡Te invito a sumarte a esta experiencia donde el agua se convierte en bienestar, salud y alegría!"

      - label: "Texto principal - Nuestro Club"
        name: "texto_principal"
        widget: "markdown"

      - label: "Título - Objetivos"
        name: "titulo_objetivos"
        widget: "string"
        default: "Nuestros Objetivos"

      - label: "Lista de Objetivos"
        name: "lista_objetivos"
        widget: "markdown"
        default: |
          - **Fomentar un estilo de vida saludable y activo**, promoviendo hábitos que mejoren el bienestar físico y emocional de nuestros alumnos.
          - **Impulsar la práctica regular de actividad física** adaptada a todas las edades y capacidades.
          - **Transmitir seguridad y confianza en el medio acuático** creando un entorno seguro, motivador y adaptado al ritmo de cada persona.
          - **Ofrecer un trato cercano y personalizado** fortaleciendo la relación con nuestros alumnos y sus familias.
          - **Enseñar desde la pasión y la experiencia**, compartiendo los conocimientos técnicos necesarios para disfrutar del deporte acuático con autonomía y seguridad.

      - label: "Título - ¿Dónde estamos?"
        name: "titulo_estamos"
        widget: "string"
        default: "¿Dónde Estamos?"

      - label: "Lista de Ubicación"
        name: "lista_estamos"
        widget: "markdown"
        default: |
          - **Dirección:** Albergue Inturjoven Aguadulce en Verano y Hotel Playadulce el resto del año  
          - **Horario:** Consultar por WhatsApp o E-mail  
          - **Teléfono:** 659 13 69 87  
          - **Email:** natacion_aguadulce@outlook.es



          # -------------------------------
          # 3. Aquagym
          # -------------------------------
          - label: "Aquagym"
            name: "aquagym"
            widget: "object"
            required: false
            fields:
              - { name: "titulo_seccion", label: "Título Sección", widget: "string", required: false }
              - { name: "descripcion", label: "Descripción", widget: "markdown", required: false }
              - { name: "texto_fijo", label: "Texto Destacado", widget: "text", required: false }
              
              - label: "Beneficios"
                name: "beneficios"
                widget: "list"
                required: false
                field: { label: "Beneficio", name: "item", widget: "text", required: false }
              
              - label: "Horarios"
                name: "horarios"
                widget: "object"
                required: false
                fields:
                  - { name: "verano", label: "Horario Verano", widget: "markdown", required: false }
                  - { name: "invierno", label: "Horario Invierno", widget: "markdown", required: false }

          # -------------------------------
          # 4. Matronatación
          # -------------------------------
          - label: "Matronatación"
            name: "matronatacion"
            widget: "object"
            required: false
            fields:
              - { name: "titulo_seccion", label: "Título Sección", widget: "string", required: false }
              - { name: "descripcion", label: "Descripción", widget: "markdown", required: false }
              - { name: "texto_fijo", label: "Texto Destacado", widget: "text", required: false }
              
              - label: "Beneficios"
                name: "beneficios"
                widget: "list"
                required: false
                field: { label: "Beneficio", name: "item", widget: "text", required: false }
              
              - { name: "instrucciones_reserva", label: "Instrucciones Reserva", widget: "markdown", required: false }

          # -------------------------------
          # 5. Natación
          # -------------------------------
          - label: "Natación"
            name: "natacion"
            widget: "object"
            required: false
            fields:
              - { name: "titulo_seccion", label: "Título Sección", widget: "string", required: false }
              - { name: "descripcion", label: "Descripción", widget: "markdown", required: false }
              - { name: "texto_fijo", label: "Texto Destacado", widget: "text", required: false }
              
              - label: "Beneficios"
                name: "beneficios"
                widget: "list"
                required: false
                field: { label: "Beneficio", name: "item", widget: "text", required: false }
              
              - { name: "instrucciones_reserva", label: "Instrucciones Reserva", widget: "markdown", required: false }

          # -------------------------------
          # 6. Clases Privadas
          # -------------------------------
          - label: "Clases Privadas"
            name: "clases_privadas"
            widget: "object"
            required: false
            fields:
              - { name: "titulo_seccion", label: "Título Sección", widget: "string", required: false }
              - { name: "descripcion", label: "Descripción", widget: "markdown", required: false }
              
              - label: "Ventajas"
                name: "ventajas"
                widget: "list"
                required: false
                field: { label: "Ventaja", name: "item", widget: "string", required: false }
              
              - { name: "texto_boton", label: "Texto Botón Reserva", widget: "string", required: false }

          # -------------------------------
          # 7. Galerías (nuevo)
          # -------------------------------
          - label: "Galerías"
            name: "galerias"
            widget: "object"
            required: false
            fields:
              - label: "Aquagym"
                name: "galeria_aquagym"
                widget: "list"
                required: false
                field: { label: "Imagen/Video", name: "media", widget: "file", required: false }
              
              - label: "Matronatación"
                name: "galeria_matronatacion"
                widget: "list"
                required: false
                field: { label: "Imagen/Video", name: "media", widget: "file", required: false }
              
              - label: "Natación"
                name: "galeria_natacion"
                widget: "list"
                required: false
                field: { label: "Imagen/Video", name: "media", widget: "file", required: false }

          # -------------------------------
          # 8. Contacto
          # -------------------------------
          - label: "Contacto"
            name: "contacto"
            widget: "object"
            required: false
            fields:
              - { name: "titulo_seccion", label: "Título Sección", widget: "string", required: false }
              
              - label: "Información de Contacto"
                name: "info_contacto"
                widget: "object"
                required: false
                fields:
                  - { name: "telefono", label: "Teléfono", widget: "string", required: false }
                  - { name: "email", label: "Email", widget: "string", required: false }
                  - { name: "direccion_verano", label: "Dirección (Verano)", widget: "text", required: false }
                  - { name: "direccion_invierno", label: "Dirección (Invierno)", widget: "text", required: false }
                  - { name: "instagram", label: "Usuario Instagram", widget: "string", required: false }
              
              - label: "Formulario"
                name: "formulario"
                widget: "object"
                required: false
                fields:
                  - { name: "email_destino", label: "Email Destino Formulario", widget: "string", required: false }
                  - { name: "texto_boton", label: "Texto Botón Enviar", widget: "string", required: false }

          # -------------------------------
          # 9. Footer
          # -------------------------------
          - label: "Footer"
            name: "footer"
            widget: "object"
            required: false
            fields:
              - { name: "copyright", label: "Texto Copyright", widget: "string", required: false }
              - { name: "instagram", label: "Usuario Instagram Footer", widget: "string", required: false }

# Colección para imágenes generales (opcional)
  - name: "imagenes_generales"
    label: "Imágenes Generales"
    folder: "imagenes"
    create: true
    fields:
      - { name: "imagen", label: "Archivo", widget: "image" }

  # Galería de Aquagym
  - name: "aquagym"
    label: "Aquagym - Galería"
    folder: "imagenes/Aquagym"    # Ruta exacta
    description: "Sube o gestiona imágenes/vídeos de Aquagym"
    create: true
    delete: true
    fields:
      - { name: "archivo", label: "Archivo", widget: "image", allow_multiple: false }
      - { name: "descripcion", label: "Descripción (SEO)", widget: "string", required: false }

  # Galería de Matronatación
  - name: "matronatacion"
    label: "Matronatación - Galería"
    folder: "imagenes/matronatacion"
    create: true
    delete: true
    fields:
      - { name: "archivo", label: "Archivo", widget: "image", allow_multiple: false }
      - { name: "titulo", label: "Título (opcional)", widget: "string", required: false }

  # Galería de Natación
  - name: "natacion"
    label: "Natación - Galería"
    folder: "imagenes/natacion"
    create: true
    delete: true
    fields:
      - { name: "archivo", label: "Archivo", widget: "image", allow_multiple: true }
      - { 
          name: "tipo", 
          label: "Tipo de contenido", 
          widget: "select", 
          options: ["Foto", "Video"], 
          default: "Foto" 
        }
