backend:
  name: git-gateway
  branch: main # O la rama que uses para tu sitio (e.g., master)

publish_mode: editorial_workflow # Opcional: Para permitir borradores y revisiones

media_folder: "static/uploads" # Carpeta donde Netlify CMS subirá las imágenes y videos
public_folder: "/uploads"     # Ruta pública para acceder a los medios (desde la raíz del sitio)

collections:
  - name: "pages"
    label: "Páginas del Sitio"
    files:
      - file: "content/_index.md" # Ruta al archivo Markdown de tu página principal (Hugo convention for homepage)
        label: "Página de Inicio"
        name: "index"
        fields:
          - {label: "Título de la Página", name: "title", widget: "string", default: "Clases de Natación en Aguadulce | Profesor Gastón Martín Iriart"}
          - {label: "Layout (Hugo)", name: "layout", widget: "hidden", default: "index"} # Indica a Hugo qué plantilla usar
          - label: "SEO / Meta Descripción"
            name: "description"
            widget: "string"
            default: "Clases de natación, Aquagym y Matronatación en Aguadulce para todas las edades con Gastón Martín Iriart, profesor certificado. Aprende y diviértete en un ambiente seguro."
          - label: "Información de Contacto General"
            name: "contact_info"
            widget: "object"
            fields:
              - {label: "Número de Teléfono (WhatsApp)", name: "whatsapp_number", widget: "string", pattern: ["^[0-9]+$", "Solo números (sin espacios ni guiones)"], default: "659136987"}
              - {label: "URL de Instagram", name: "instagram_url", widget: "string", default: "https://www.instagram.com/clubnatacion.aguadulce/"}
              - {label: "Email de Contacto", name: "email", widget: "string", default: "natacion_aguadulce@outlook.es"}
          - label: "Sección Hero (Inicio)"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Imagen de Fondo del Hero", name: "imagen_hero", widget: "image", default: "/uploads/hero-image-natacion.jpg"}
              - {label: "Texto sobre la imagen (opcional)", name: "texto_overlay", widget: "text", required: false} # Si quieres texto dinámico sobre la imagen hero
          - label: "Sección 'Sobre nosotros' (Club)"
            name: "sobre"
            widget: "object"
            fields:
              - {label: "Título de la Sección", name: "titulo_seccion", widget: "string", default: "Sobre nosotros"}
              - {label: "Imagen de Gastón Martín Iriart", name: "imagen_sobre_nosotros", widget: "image", default: "/uploads/Gaston-Martin-Iriart-profesor.jpg"}
              - {label: "Texto superpuesto en la imagen", name: "texto_imagen", widget: "string", default: "¡Te invito a sumarte a esta experiencia donde el agua se convierte en bienestar, salud y alegría!"}
              - label: "Contenido del Slider - Sobre el Club"
                name: "club_content"
                widget: "object"
                fields:
                  - {label: "Título", name: "titulo", widget: "string", default: "Nuestro Club"}
                  - {label: "Texto Principal", name: "texto_principal", widget: "markdown", default: "Soy Gastón Martín Iriart, graduado en Ciencias de la Actividad Física y el Deporte y Monitor de Natación por la Real Federación Española de Natación (RFEN). Llevo más de 10 años dedicado con pasión a la enseñanza de la natación..."}
              - label: "Contenido del Slider - Nuestros Objetivos"
                name: "objetivos_content"
                widget: "object"
                fields:
                  - {label: "Título", name: "titulo", widget: "string", default: "Nuestros Objetivos"}
                  - {label: "Lista de Objetivos", name: "lista_objetivos", widget: "list", field: {label: "Objetivo", name: "objetivo", widget: "markdown"}}
              - label: "Contenido del Slider - Dónde Estamos"
                name: "donde_estamos_content"
                widget: "object"
                fields:
                  - {label: "Título", name: "titulo", widget: "string", default: "¿Dónde Estamos?"}
                  - {label: "Dirección", name: "direccion", widget: "string", default: "Albergue Inturjoven Aguadulce en Verano y Hotel Playadulce el resto del año"}
                  - {label: "Horario", name: "horario", widget: "string", default: "Consultar por WhatsApp o E-mail"}
                  - {label: "Teléfono", name: "telefono", widget: "string", default: "659 13 69 87"}
                  - {label: "Email", name: "email", widget: "string", default: "natacion_aguadulce@outlook.es"}

          - label: "Sección Aquagym"
            name: "aquagym_section"
            widget: "object"
            fields:
              - {label: "Título de la Sección", name: "titulo_seccion", widget: "string", default: "Aquagym"}
              - {label: "Imágenes del Carrusel (para la sección Aquagym)", name: "carrusel_imagenes", widget: "list", field: {label: "Imagen", name: "imagen", widget: "image"}}
              - {label: "Texto superpuesto en la imagen", name: "texto_fijado", widget: "string", default: "No necesitas saber nadar, ¡solo tener ganas de moverte, reír y sentirte mejor!"}
              - label: "Contenido del Slider - Sobre Aquagym"
                name: "sobre_aquagym_content"
                widget: "object"
                fields:
                  - {label: "Título", name: "titulo", widget: "string", default: "¡Descubre el Aquagym!"}
                  - {label: "Texto", name: "texto", widget: "markdown", default: "El **Aquagym** es una actividad física acuática que combina ejercicios de gimnasia..."}
              - label: "Contenido del Slider - Beneficios Aquagym"
                name: "beneficios_aquagym_content"
                widget: "object"
                fields:
                  - {label: "Título", name: "titulo", widget: "string", default: "Objetivos del Aquagym"}
                  - {label: "Lista de Beneficios", name: "lista_beneficios", widget: "list", field: {label: "Beneficio", name: "beneficio", widget: "markdown"}}
                  - {label: "Texto Adicional", name: "texto_adicional", widget: "markdown", required: false}
              - label: "Contenido del Slider - Horarios Aquagym"
                name: "horarios_aquagym_content"
                widget: "object"
                fields:
                  - {label: "Título", name: "titulo", widget: "string", default: "Horarios de Aquagym"}
                  - {label: "Horarios de Verano", name: "horarios_verano", widget: "markdown", default: "#### Horarios de Verano\n* **Lunes, Miércoles y Viernes...**"}
                  - {label: "Horarios de Invierno", name: "horarios_invierno", widget: "markdown", default: "#### Horarios de Invierno (grupos reducidos)\n* **Lunes, Miércoles y Viernes...**"}

          # --- Repite la estructura para Matronatación y Natación 2025 ---
          - label: "Sección Matronatación"
            name: "matronatacion_section"
            widget: "object"
            fields:
              - {label: "Título de la Sección", name: "titulo_seccion", widget: "string", default: "Matronatación"}
              - {label: "Imágenes del Carrusel (para la sección Matronatación)", name: "carrusel_imagenes", widget: "list", field: {label: "Imagen", name: "imagen", widget: "image"}}
              - {label: "Texto superpuesto en la imagen", name: "texto_fijado", widget: "string", default: "¡La mejor forma de fortalecer el vínculo con tu bebé mientras se divierten en el agua!"}
              - label: "Contenido del Slider - Sobre Matronatación"
                name: "sobre_matronatacion_content"
                widget: "object"
                fields:
                  - {label: "Título", name: "titulo", widget: "string", default: "¡Descubre la Matronatación!"}
                  - {label: "Texto", name: "texto", widget: "markdown", default: "La **Matronatación** es una actividad acuática especial..."}
              - label: "Contenido del Slider - Beneficios Matronatación"
                name: "beneficios_matronatacion_content"
                widget: "object"
                fields:
                  - {label: "Título", name: "titulo", widget: "string", default: "Beneficios de la Matronatación"}
                  - {label: "Lista de Beneficios", name: "lista_beneficios", widget: "list", field: {label: "Beneficio", name: "beneficio", widget: "markdown"}}
                  - {label: "Texto Adicional", name: "texto_adicional", widget: "markdown", required: false}
              - label: "Contenido del Slider - Horarios Matronatación"
                name: "horarios_matronatacion_content"
                widget: "object"
                fields:
                  - {label: "Título", name: "titulo", widget: "string", default: "Horarios de Matronatación"}
                  - {label: "Horarios de Verano", name: "horarios_verano", widget: "markdown", default: "#### Horarios de Verano\n* **Lunes, Miércoles y Viernes...**"}
                  - {label: "Horarios de Invierno", name: "horarios_invierno", widget: "markdown", default: "#### Horarios de Invierno (grupos reducidos)\n* **Lunes, Miércoles y Viernes...**"}

          - label: "Sección Natación 2025"
            name: "natacion_section"
            widget: "object"
            fields:
              - {label: "Título de la Sección", name: "titulo_seccion", widget: "string", default: "Natación 2025"}
              - {label: "Imágenes del Carrusel (para la sección Natación)", name: "carrusel_imagenes", widget: "list", field: {label: "Imagen", name: "imagen", widget: "image"}}
              - {label: "Texto superpuesto en la imagen", name: "texto_fijado", widget: "string", default: "¡Aprende a nadar o perfecciona tu estilo, el agua te espera!"}
              - label: "Contenido del Slider - Sobre Natación"
                name: "sobre_natacion_content"
                widget: "object"
                fields:
                  - {label: "Título", name: "titulo", widget: "string", default: "¡Sumérgete en la Natación!"}
                  - {label: "Texto", name: "texto", widget: "markdown", default: "La **Natación** es uno de los deportes más completos..."}
              - label: "Contenido del Slider - Beneficios Natación"
                name: "beneficios_natacion_content"
                widget: "object"
                fields:
                  - {label: "Título", name: "titulo", widget: "string", default: "Beneficios de la Natación"}
                  - {label: "Lista de Beneficios", name: "lista_beneficios", widget: "list", field: {label: "Beneficio", name: "beneficio", widget: "markdown"}}
                  - {label: "Texto Adicional", name: "texto_adicional", widget: "markdown", required: false}
              - label: "Contenido del Slider - Horarios Natación"
                name: "horarios_natacion_content"
                widget: "object"
                fields:
                  - {label: "Título", name: "titulo", widget: "string", default: "Horarios de Natación"}
                  - {label: "Horarios de Verano", name: "horarios_verano", widget: "markdown", default: "#### Horarios de Verano\n* **Lunes, Miércoles y Viernes...**"}
                  - {label: "Horarios de Invierno", name: "horarios_invierno", widget: "markdown", default: "#### Horarios de Invierno (grupos reducidos)\n* **Lunes, Miércoles y Viernes...**"}

          - label: "Sección Clases Privadas"
            name: "clases_privadas_section"
            widget: "object"
            fields:
              - {label: "Título de la Sección", name: "titulo_seccion", widget: "string", default: "Clases Privadas Personalizadas"}
              - {label: "Imagen de Clases Privadas", name: "imagen", widget: "image", default: "/uploads/clases-particulares.jpg"}
              - {label: "Texto principal", name: "texto_principal", widget: "markdown", default: "Ofrezco clases particulares de natación..."}
              - {label: "Beneficios de Clases Privadas", name: "lista_beneficios", widget: "list", field: {label: "Beneficio", name: "beneficio", widget: "markdown"}}

          - label: "Sección Ubicación"
            name: "ubicacion_section"
            widget: "object"
            fields:
              - {label: "Título de la Sección", name: "titulo_seccion", widget: "string", default: "Ubicación"}
              - {label: "Texto", name: "texto", widget: "markdown", default: "Estamos convenientemente ubicados para ofrecerte las mejores instalaciones..."}
              - {label: "Texto de la dirección", name: "texto_direccion", widget: "string", default: "Albergue Inturjoven Aguadulce (en verano) y Hotel Playadulce (resto del año)."}
              - {label: "Latitud (Mapa)", name: "latitude", widget: "string", default: "36.8068027"}
              - {label: "Longitud (Mapa)", name: "longitude", widget: "string", default: "-2.5741880"}
              - {label: "Enlace a Google Maps", name: "google_maps_link", widget: "string", default: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3198.818047913507!2d-2.574188031388062!3d36.80680267073281!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd7ae0d6360c7f21%3A0xc3f6d7d519b5c3ee!2sHotel%20Playadulce!5e0!3m2!1ses!2ses!4v1689728860000!5m2!1ses!2ses"}

          - label: "Sección Contacto"
            name: "contacto_section"
            widget: "object"
            fields:
              - {label: "Título de la Sección", name: "titulo_seccion", widget: "string", default: "Contacto"}
              - {label: "Texto", name: "texto", widget: "markdown", default: "No dudes en contactarnos para cualquier consulta..."}
              - {label: "Teléfono", name: "telefono", widget: "string", default: "659 13 69 87"}
              - {label: "Email", name: "email", widget: "string", default: "natacion_aguadulce@outlook.es"}
              - {label: "Texto del formulario (opcional)", name: "form_text", widget: "string", default: "Déjanos tu mensaje y te contactaremos en breve."}

  # --- Colecciones para las galerías ---
  # Cada galería será un archivo JSON que contendrá una lista de sus medios
  - name: "aquagym_gallery"
    label: "Galería de Aquagym"
    folder: "data/galleries/aquagym" # Carpeta donde se guardarán los archivos de la galería
    create: true # Permite crear nuevas entradas
    fields:
      - {label: "Título (Interno)", name: "title", widget: "string", required: true}
      - {label: "Tipo de Medio", name: "type", widget: "select", options: ["image", "video"], default: "image"}
      - {label: "Archivo de Medio", name: "media_file", widget: "file"} # Usamos 'file' para aceptar ambos tipos
      - {label: "Leyenda", name: "caption", widget: "string", required: false}

  - name: "matronatacion_gallery"
    label: "Galería de Matronatación"
    folder: "data/galleries/matronatacion"
    create: true
    fields:
      - {label: "Título (Interno)", name: "title", widget: "string", required: true}
      - {label: "Tipo de Medio", name: "type", widget: "select", options: ["image", "video"], default: "image"}
      - {label: "Archivo de Medio", name: "media_file", widget: "file"}
      - {label: "Leyenda", name: "caption", widget: "string", required: false}

  - name: "natacion_gallery"
    label: "Galería de Natación"
    folder: "data/galleries/natacion"
    create: true
    fields:
      - {label: "Título (Interno)", name: "title", widget: "string", required: true}
      - {label: "Tipo de Medio", name: "type", widget: "select", options: ["image", "video"], default: "image"}
      - {label: "Archivo de Medio", name: "media_file", widget: "file"}
      - {label: "Leyenda", name: "caption", widget: "string", required: false}
