backend:
  name: git-gateway
  branch: main
media_folder: "imagenes"
public_folder: "/imagenes"
publish_mode: editorial_workflow

collections:
  - name: "pagina_principal"
    label: "Página Principal"
    editor:
      preview: false
    files:
      - name: "inicio"
        label: "Contenido Principal"
        file: "../index.html"
        fields:
          # -------------------------------
          # 1. Hero Section
          # -------------------------------
          - label: "Hero Banner"
            name: "hero"
            widget: "object"
            fields:
              - { name: "titulo", label: "Título Principal", widget: "string", required: false }
              - { name: "texto_boton", label: "Texto Botón Principal", widget: "string" }
              - { name: "texto_boton_whatsapp", label: "Texto Botón WhatsApp", widget: "string" }

          # -------------------------------
          # 2. Sobre Nosotros
          # -------------------------------
          - label: "Sobre Nosotros"
            name: "sobre_nosotros"
            widget: "object"
            collapsed: true
            fields:
              - { name: "titulo_seccion", label: "Título Sección", widget: "string" }
              - { name: "texto_principal", label: "Texto Principal", widget: "markdown" }
              - { name: "texto_imagen", label: "Texto sobre Imagen", widget: "text" }
              
              - label: "Objetivos"
                name: "objetivos"
                widget: "list"
                field: { label: "Objetivo", name: "item", widget: "text" }
              
              - label: "Ubicación"
                name: "ubicacion"
                widget: "object"
                fields:
                  - { name: "direccion", label: "Dirección", widget: "string" }
                  - { name: "horario", label: "Horario", widget: "string" }
                  - { name: "telefono", label: "Teléfono", widget: "string" }
                  - { name: "email", label: "Email", widget: "string" }

          # -------------------------------
          # 3. Aquagym
          # -------------------------------
          - label: "Aquagym"
            name: "aquagym"
            widget: "object"
            collapsed: true
            fields:
              - { name: "titulo_seccion", label: "Título Sección", widget: "string" }
              - { name: "descripcion", label: "Descripción", widget: "markdown" }
              - { name: "texto_fijo", label: "Texto Destacado", widget: "text" }
              
              - label: "Beneficios"
                name: "beneficios"
                widget: "list"
                field: { label: "Beneficio", name: "item", widget: "text" }
              
              - label: "Horarios"
                name: "horarios"
                widget: "object"
                fields:
                  - { name: "verano", label: "Horario Verano", widget: "markdown" }
                  - { name: "invierno", label: "Horario Invierno", widget: "markdown" }

          # -------------------------------
          # 4. Matronatación
          # -------------------------------
          - label: "Matronatación"
            name: "matronatacion"
            widget: "object"
            collapsed: true
            fields:
              - { name: "titulo_seccion", label: "Título Sección", widget: "string" }
              - { name: "descripcion", label: "Descripción", widget: "markdown" }
              - { name: "texto_fijo", label: "Texto Destacado", widget: "text" }
              
              - label: "Beneficios"
                name: "beneficios"
                widget: "list"
                field: { label: "Beneficio", name: "item", widget: "text" }
              
              - { name: "instrucciones_reserva", label: "Instrucciones Reserva", widget: "markdown" }

          # -------------------------------
          # 5. Natación
          # -------------------------------
          - label: "Natación"
            name: "natacion"
            widget: "object"
            collapsed: true
            fields:
              - { name: "titulo_seccion", label: "Título Sección", widget: "string" }
              - { name: "descripcion", label: "Descripción", widget: "markdown" }
              - { name: "texto_fijo", label: "Texto Destacado", widget: "text" }
              
              - label: "Beneficios"
                name: "beneficios"
                widget: "list"
                field: { label: "Beneficio", name: "item", widget: "text" }
              
              - { name: "instrucciones_reserva", label: "Instrucciones Reserva", widget: "markdown" }

          # -------------------------------
          # 6. Clases Privadas
          # -------------------------------
          - label: "Clases Privadas"
            name: "clases_privadas"
            widget: "object"
            collapsed: true
            fields:
              - { name: "titulo_seccion", label: "Título Sección", widget: "string" }
              - { name: "descripcion", label: "Descripción", widget: "markdown" }
              
              - label: "Ventajas"
                name: "ventajas"
                widget: "list"
                field: { label: "Ventaja", name: "item", widget: "string" }
              
              - { name: "texto_boton", label: "Texto Botón Reserva", widget: "string" }

          # -------------------------------
          # 7. Contacto
          # -------------------------------
          - label: "Contacto"
            name: "contacto"
            widget: "object"
            collapsed: true
            fields:
              - { name: "titulo_seccion", label: "Título Sección", widget: "string" }
              
              - label: "Información de Contacto"
                name: "info_contacto"
                widget: "object"
                fields:
                  - { name: "telefono", label: "Teléfono", widget: "string" }
                  - { name: "email", label: "Email", widget: "string" }
                  - { name: "direccion_verano", label: "Dirección (Verano)", widget: "text" }
                  - { name: "direccion_invierno", label: "Dirección (Invierno)", widget: "text" }
                  - { name: "instagram", label: "Usuario Instagram", widget: "string" }
              
              - label: "Formulario"
                name: "formulario"
                widget: "object"
                fields:
                  - { name: "email_destino", label: "Email Destino Formulario", widget: "string" }
                  - { name: "texto_boton", label: "Texto Botón Enviar", widget: "string" }

          # -------------------------------
          # 8. Footer
          # -------------------------------
          - label: "Footer"
            name: "footer"
            widget: "object"
            collapsed: true
            fields:
              - { name: "copyright", label: "Texto Copyright", widget: "string" }
              - { name: "instagram", label: "Usuario Instagram Footer", widget: "string" }

# Colección para imágenes generales (opcional)
  - name: "imagenes_generales"
    label: "Imágenes Generales"
    folder: "imagenes"
    create: true
    fields:
      - { name: "imagen", label: "Archivo", widget: "image" }

  # Galería de Aquagym
  - name: "aquagym"
    label: "Aquagym - Galería"
    folder: "imagenes/Aquagym"    # Ruta exacta
    description: "Sube o gestiona imágenes/vídeos de Aquagym"
    create: true
    delete: true
    fields:
      - { name: "archivo", label: "Archivo", widget: "image", allow_multiple: false }
      - { name: "descripcion", label: "Descripción (SEO)", widget: "string", required: false }

  # Galería de Matronatación
  - name: "matronatacion"
    label: "Matronatación - Galería"
    folder: "imagenes/matronatacion"
    create: true
    delete: true
    fields:
      - { name: "archivo", label: "Archivo", widget: "image", allow_multiple: false }
      - { name: "titulo", label: "Título (opcional)", widget: "string", required: false }

  # Galería de Natación
  - name: "natacion"
    label: "Natación - Galería"
    folder: "imagenes/natacion"
    create: true
    delete: true
    fields:
      - { name: "archivo", label: "Archivo", widget: "image", allow_multiple: true }
      - { 
          name: "tipo", 
          label: "Tipo de contenido", 
          widget: "select", 
          options: ["Foto", "Video"], 
          default: "Foto" 
        }
